// <auto-generated />
using System;
using CountriesGdpDirectory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CountriesGdpDirectory.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230304200633_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CountriesGdpDirectory.Models.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GDPId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GDPId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CountriesGdpDirectory.Models.Entities.GDP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Gdp")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GdpPPP")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GdpPerCapita")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GdpPerCapitaPPP")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("GDPs");
                });

            modelBuilder.Entity("CountriesGdpDirectory.Models.Entities.Country", b =>
                {
                    b.HasOne("CountriesGdpDirectory.Models.Entities.GDP", "GDP")
                        .WithMany("Countries")
                        .HasForeignKey("GDPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GDP");
                });

            modelBuilder.Entity("CountriesGdpDirectory.Models.Entities.GDP", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
